server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${SPRING_DATASOURCE_USERNAME:bank_user}
    password: ${SPRING_DATASOURCE_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/migration/master.yml

springdoc:
  api-docs:
    path: ${API_DOCS_PATH:/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
  writer-with-default-pretty-printer: true

jwt:
  secret: ${JWT_SECRET:5367566859703373367639792F423F452848284D6251655468576D5A71347437}
  expiration: ${JWT_EXPIRATION:86400000}